### ISSUE TITLE
CKAN submission module for scrapers

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/PDAP-Scrapers#173]
## Task:
- [ ] Make a python module to be called at the end of a scraper.py file that takes the output of a scraper and submits it to our CKAN instance. This can be a pretty informal experiment.
- [ ] we shouldn't submit the Extraction without a successful archive (see https://github.com/Police-Data-Accessibility-Project/PDAP-Scrapers/issues/180)
- [ ] must also submit `metadata.py` (https://github.com/Police-Data-Accessibility-Project/PDAP-Scrapers/issues/154)

### CKAN demo environment: 
https://demo.dev.datopian.com/organization/pdap-io

### CKAN API info: 
https://github.com/ckan/ckanapi
https://github.com/ckan/ckanapi#ckanapi-python-module
